# Generated by Django 4.1.5 on 2023-02-09 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_cart_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart_new",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                unique=True,
            ),
        ),
    ]
