# Generated by Django 4.1.5 on 2023-02-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
