# Generated by Django 4.1.5 on 2023-02-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_orders_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart_new", name="quantity", field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="orders", name="quantity", field=models.SmallIntegerField(),
        ),
    ]
