# Generated by Django 4.1.5 on 2023-02-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_alter_cart_new_quantity_alter_orders_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders", name="date", field=models.DateTimeField(auto_now=True),
        ),
    ]
