# Generated by Django 4.1.5 on 2023-02-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_remove_orders_order_orderproduct"),
    ]

    operations = [
        migrations.RemoveField(model_name="orders", name="product",),
        migrations.AddField(
            model_name="orders",
            name="product",
            field=models.ManyToManyField(to="product.product"),
        ),
    ]
