# Generated by Django 4.1.5 on 2023-02-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_remove_orders_product_orders_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="quantity",
            field=models.SmallIntegerField(null=True),
        ),
    ]
